name: "Workflow Event Test"
description: "Test the workflow event"
author: Bullrich
branding:
  icon: list
  color: red
inputs:
  TOKEN:
    required: true
    description: Private Access Token with the scope repo
  repo:
    required: false
    description: The repo to analyze
  org:
    required: false
    description: The organization that owns the repo

runs:
  using: 'docker'
  image: 'Dockerfile'
